### ISSUE TITLE
SVG Approval

### ISSUE THREAD

**Issue by GiacomoCorradini** [GiacomoCorradini/TpaHomework1#2]
Buongiorno @DavidLeoni,

Nella repositories è presente il file SVG, macchina, che ho pensato di fare.
I parametri da utilizzare sono:

- Altezza del veicolo
- Lunghezza del veicolo
- Dimensioni delle ruote

Le chiedo se può andare bene l'idea in modo da poter continuare il lavoro.

Cordiali saluti

**Comment by DavidLeoni** [comment]
Magari aggiungerei anche posizione x delle ruote, così hai qualche vincolo in più da controllare

**Comment by GiacomoCorradini** [comment]
Ok grazie

**Comment by GiacomoCorradini** [comment]
@DavidLeoni 
Ok grazie
